<?php

namespace ContainerB7aJS59;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\Classification\ConsoleController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\Classification\ConsoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/Classification/ConsoleController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Classification/FindAllConsoles.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/ResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/AbstractResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/Classification/ConsoleResponseDtoTransformer.php';

        $container->services['App\\Backend\\Infrastructure\\Controller\\Classification\\ConsoleController'] = $instance = new \App\Backend\Infrastructure\Controller\Classification\ConsoleController(new \App\Backend\Application\UseCases\Classification\FindAllConsoles(($container->privates['App\\Backend\\Infrastructure\\Repository\\Classification\\DoctrineConsoleRepository'] ?? $container->load('getDoctrineConsoleRepositoryService')), new \App\Backend\Application\Dto\Response\Transform\Classification\ConsoleResponseDtoTransformer()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Backend\\Infrastructure\\Controller\\Classification\\ConsoleController', $container));

        return $instance;
    }
}
