<?php

namespace ContainerB7aJS59;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\Order\ItemController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\Order\ItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/Order/ItemController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Order/FindAllItem.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/ResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/AbstractResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/Order/ItemResponseDtoTransformer.php';

        $container->services['App\\Backend\\Infrastructure\\Controller\\Order\\ItemController'] = $instance = new \App\Backend\Infrastructure\Controller\Order\ItemController(new \App\Backend\Application\UseCases\Order\FindAllItem(($container->privates['App\\Backend\\Infrastructure\\Repository\\Order\\DoctrineItemRepository'] ?? $container->load('getDoctrineItemRepositoryService')), new \App\Backend\Application\Dto\Response\Transform\Order\ItemResponseDtoTransformer()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Backend\\Infrastructure\\Controller\\Order\\ItemController', $container));

        return $instance;
    }
}
