<?php

namespace ContainerB7aJS59;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\Order\OrderController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\Order\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/Order/OrderController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Order/FindAOrder.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/ResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/AbstractResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/Order/OrderResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Order/FindAllOrders.php';

        $a = ($container->privates['App\\Backend\\Infrastructure\\Repository\\Order\\DoctrineOrderRepository'] ?? $container->load('getDoctrineOrderRepositoryService'));
        $b = new \App\Backend\Application\Dto\Response\Transform\Order\OrderResponseDtoTransformer();

        $container->services['App\\Backend\\Infrastructure\\Controller\\Order\\OrderController'] = $instance = new \App\Backend\Infrastructure\Controller\Order\OrderController(new \App\Backend\Application\UseCases\Order\FindAOrder($a, $b), new \App\Backend\Application\UseCases\Order\FindAllOrders($a, $b));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Backend\\Infrastructure\\Controller\\Order\\OrderController', $container));

        return $instance;
    }
}
