<?php

namespace ContainerB7aJS59;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRafaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\RafaController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\RafaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/RafaController.php';

        return $container->services['App\\Backend\\Infrastructure\\Controller\\RafaController'] = new \App\Backend\Infrastructure\Controller\RafaController();
    }
}
