version: '3.1'

services:
  confd:
    container_name: confd
    image: dockage/confd:latest
    command: "confd -interval 2 -backend etcd -node=http://0.0.0.0:2379"
    network_mode: "host"
    volumes: 
      - ./etc/confd:/etc/confd
      - ./etc/vgweb:/etc/vgweb