version: '3.1'

services:
  db:
    container_name: mysql
    image: mariadb:10.5.9-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  
  balancer:
    container_name: balancer
    image: nginx:1.19.8
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"