version: '3.1'

services:
  db:
    container_name: mysql
    image: mariadb:10.5.9-focal
    tty: true
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  
  balancer:
    container_name: balancer
    image: nginx:1.19.8
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./VGWeb/vgweb:/var/www/html
      - ./etc/nginx_production/nginx.conf:/etc/nginx/conf.d/site.conf
    links: 
      - app

  app:
    container_name: vgweb
    build: .
    ports:
      - "8443:80"
    volumes:
      - ./VGWeb/vgweb:/var/www/html
    depends_on:
      - db
