<?php

namespace ContainerGDiLnCZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLuckyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\LuckyController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\LuckyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/LuckyController.php';

        return $container->services['App\\Backend\\Infrastructure\\Controller\\LuckyController'] = new \App\Backend\Infrastructure\Controller\LuckyController();
    }
}
