<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7aJS59\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7aJS59/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7aJS59.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7aJS59\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPMwK3HM\App_KernelDevDebugContainer([
    'container.build_hash' => 'PMwK3HM',
    'container.build_id' => '9bc9e0a7',
    'container.build_time' => 1620754832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPMwK3HM');
