<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJdYSwUm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJdYSwUm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJdYSwUm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJdYSwUm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJdYSwUm\App_KernelDevDebugContainer([
    'container.build_hash' => 'JdYSwUm',
    'container.build_id' => 'a2088c57',
    'container.build_time' => 1620155351,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJdYSwUm');
