<?php

namespace ContainerPMwK3HM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\Order\ProductController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\Order\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/Order/ProductController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Order/FindAllProducts.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/ResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/AbstractResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/Order/ProductResponseDtoTransformer.php';

        $container->services['App\\Backend\\Infrastructure\\Controller\\Order\\ProductController'] = $instance = new \App\Backend\Infrastructure\Controller\Order\ProductController(new \App\Backend\Application\UseCases\Order\FindAllProducts(($container->privates['App\\Backend\\Infrastructure\\Repository\\Order\\DoctrineProductRepository'] ?? $container->load('getDoctrineProductRepositoryService')), new \App\Backend\Application\Dto\Response\Transform\Order\ProductResponseDtoTransformer()));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', true],
            'security.csrf.token_manager' => ['services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'session' => ['services', 'session', 'getSessionService', true],
            'twig' => ['services', 'twig', 'getTwigService', true],
        ], [
            'doctrine' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'session' => '?',
            'twig' => '?',
        ]))->withContext('App\\Backend\\Infrastructure\\Controller\\Order\\ProductController', $container));

        return $instance;
    }
}
