<?php

namespace ContainerEHyFXdQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\Classification\CategoryController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\Classification\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/Classification/CategoryController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Classification/FindAllCategories.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/ResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/AbstractResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/Classification/CategoryResponseDtoTransformer.php';

        $container->services['App\\Backend\\Infrastructure\\Controller\\Classification\\CategoryController'] = $instance = new \App\Backend\Infrastructure\Controller\Classification\CategoryController(new \App\Backend\Application\UseCases\Classification\FindAllCategories(($container->privates['App\\Backend\\Infrastructure\\Repository\\Classification\\DoctrineCategoryRepository'] ?? $container->load('getDoctrineCategoryRepositoryService')), new \App\Backend\Application\Dto\Response\Transform\Classification\CategoryResponseDtoTransformer()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Backend\\Infrastructure\\Controller\\Classification\\CategoryController', $container));

        return $instance;
    }
}
