<?php

namespace ContainerEHyFXdQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Backend\Infrastructure\Controller\Order\ProductController' shared autowired service.
     *
     * @return \App\Backend\Infrastructure\Controller\Order\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Infrastructure/Controller/Order/ProductController.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/UseCases/Order/FindAllProducts.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/ResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/AbstractResponseDtoTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Backend/Application/Dto/Response/Transform/Order/ProductResponseDtoTransformer.php';

        $container->services['App\\Backend\\Infrastructure\\Controller\\Order\\ProductController'] = $instance = new \App\Backend\Infrastructure\Controller\Order\ProductController(new \App\Backend\Application\UseCases\Order\FindAllProducts(($container->privates['App\\Backend\\Infrastructure\\Repository\\Order\\DoctrineProductRepository'] ?? $container->load('getDoctrineProductRepositoryService')), new \App\Backend\Application\Dto\Response\Transform\Order\ProductResponseDtoTransformer()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Backend\\Infrastructure\\Controller\\Order\\ProductController', $container));

        return $instance;
    }
}
